### ISSUE TITLE
Can't filter on schema.Connection for a sub-resource ID

### ISSUE THREAD

**Issue by smyrman** [rs/rest-layer#130]
Using the rest package, given a resource "as" with a sub-resource "bs", it's not possible by default to retireve "as" filtered by a "bs" id. See schema in #129.

Here is the error:

```yaml
$ bat GET :2015/api/as Authorization:"Bearer ${KEY}" filter='{bs:"59b1ac28cee0fb0001ea7330"}'
GET /api/meta/as?filter=%7Bbs%3A%2259b1ac28cee0fb0001ea7330%22%7D HTTP/1.1
Host: localhost:2015
Accept: application/json
Accept-Encoding: gzip, deflate
Authorization: Bearer XXX
User-Agent: bat/0.1.0

HTTP/1.1 422 Unprocessable Entity
Content-Length : 80
Content-Type : application/json
Date : Thu, 07 Sep 2017 21:02:24 GMT
Server : Caddy

{
  "code": 422,
  "message": "Invalid `filter` parameter: bs: field is not filterable"
}
```

To "fix" it, I tried to set "Filterable" above this line:
https://github.com/rs/rest-layer/blob/b96a9fac46d267ad2894ec98b0bf242a703a45a9/resource/resource.go#L144

Or for that matter, add a Filed in the parent schema for "bs", and set Filterable = true there. The result when trying to filter on a "bs" id, is then an empty list instead, which is also wrong.
