### ISSUE TITLE
go dep failed to init

### ISSUE THREAD

**Issue by cmorent** [rs/rest-layer#135]
I'm trying to use `dep init` from inside a project using `rest-layer` along with `rest-layer-mongo` but I got the following error:

```
No versions of github.com/rs/rest-layer-mongo met constraints:
	master: Could not introduce github.com/rs/rest-layer-mongo@master, as it requires package github.com/rs/rest-layer/schema/query from github.com/rs/rest-layer, but in version v0.1.0 that package is missing.
	query-lookup: Could not introduce github.com/rs/rest-layer-mongo@query-lookup, as it requires package github.com/rs/rest-layer/schema/query from github.com/rs/rest-layer, but in version v0.1.0 that package is missing.
```

It seems that the solution would be to tag a new release, any thoughts? 

Thanks !

**Comment by smyrman** [comment]
Hi, we haven't set up a any dep files for the rest-layer repos yet, and while there is a release of rest-layer, there is no release of rest-layer-mongo. 

I am using the following constraints for rest-layer atm. to make it work with `dep` in `Gopkg.toml`:

```toml
[[constraint]]
  name = "github.com/rs/rest-layer"
  branch = "master"

[[constraint]]
  name = "github.com/rs/rest-layer-mongo"
  branch = "master"
```
